# Generated by Django 5.2.8 on 2025-11-15 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a product image', upload_to='products/%Y/%m/%d')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for the image (for accessibility/SEO)', max_length=255)),
                ('is_main', models.BooleanField(default=False, help_text='Check if this is the main image for the product.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['is_main', 'id'],
            },
        ),
    ]
